apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-store-sa
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true