apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/vault-spike.git
    path: registry/k1-vault-spike/components/cert-manager
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
