apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuers-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/vault-spike.git
    path: registry/argocd-sync/components/cluster-issuers
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-issuers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
