# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ingress-nginx-components
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "20"
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jarededwards/vault-spike.git
#     path: registry/argocd-sync/components/ingress-nginx
#     targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: ingress-nginx
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
