apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-toolkit
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  template:
    spec:
      containers:
        - name: kubernetes-toolkit
          args:
            [
              'wait-for',
              'deployment',
              '--namespace',
              'external-dns',
              '--label',
              'app.kubernetes.io/name=external-dns',
            ]