apiVersion: batch/v1
kind: Job
metadata:
  name: postsync
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: wait
        image: sverrirab/sleep
        command:
        - /bin/sh
        - -c
        - |
          echo postsync
          sleep 30
      restartPolicy: Never
  backoffLimit: 1