apiVersion: batch/v1
kind: Job
metadata:
  name: sync-wave-10
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: atlantis-wait
        image: sverrirab/sleep
        command:
        - /bin/sh
        - -c
        - |
          echo sync wave 10
          sleep 1
      restartPolicy: Never
  backoffLimit: 1