apiVersion: batch/v1
kind: Job
metadata:
  name: sync-100-wave-10
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync #! as next test move this to a presync hook on wave 20
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: atlantis-wait
        image: sverrirab/sleep
        command:
        - /bin/sh
        - -c
        - |
          echo sync wave 100
          sleep 10
      restartPolicy: Never
  backoffLimit: 1