apiVersion: batch/v1
kind: Job
metadata:
  name: sync-30-wave-10-
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: atlantis-wait
        image: sverrirab/sleep
        command:
        - /bin/sh
        - -c
        - |
          echo "sync wave 30"
          sleep 20
      restartPolicy: Never
  backoffLimit: 1