apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wait-external-dns-deployments
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubefirst/manifests'
    path: kubernetes-toolkit/argo-wait/overlays/external-dns
    targetRevision: feat-kubernetes-toolkit
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
