apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wait-ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
    # argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubefirst/manifests'
    path: kubernetes-toolkit/argo-wait/overlays/ingress-nginx
    targetRevision: feat-kubernetes-toolkit
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
