apiVersion: batch/v1
kind: Job
metadata:
  name: sync-100-wave-20
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: atlantis-wait
        image: sverrirab/sleep
        command:
        - /bin/sh
        - -c
        - |
          echo sync wave 100
          sleep 10
      restartPolicy: Never
  backoffLimit: 1