apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume-dont-use
  namespace: minio
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/tmp/minio-storage'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim-dont-use
  namespace: minio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
