apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-toolkit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-toolkit
  annotations:
    argocd.argoproj.io/sync-wave: '0'
rules:
  - apiGroups: ['apps']
    resources: ['deployments', 'statefulsets']
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-toolkit
  annotations:
    argocd.argoproj.io/sync-wave: '0'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-toolkit
subjects:
  - kind: ServiceAccount
    name: kubernetes-toolkit
    namespace: argocd