apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-volume
  namespace: minio
  labels:
    type: local
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/tmp/minio-storage'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
