apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: argocd-volume-burn
#   namespace: argocd
#   labels:
#     type: local
#   annotations:
#     argocd.argoproj.io/sync-wave: '0'
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: '/tmp/minio-storage'
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: argocd-claim-burn
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: '0'
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
